<a href="https://colab.research.google.com/github/MnthnShrmaa/Foreign-Direct-Investment/blob/main/FDI_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data= pd.read_csv('/content/FDI data.csv')
data.head()

,Sector,2000-01,2001-02,2002-03,2003-04,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17
0,METALLURGICAL INDUSTRIES,22.69,14.14,36.61,8.11,200.38,149.13,169.94,1175.75,959.94,419.88,1098.14,1786.14,1466.23,567.63,359.34,456.31,1440.18
1,MINING,1.32,6.52,10.06,23.48,9.92,7.40,6.62,444.36,34.16,174.40,79.51,142.65,57.89,12.73,684.39,520.67,55.75
2,POWER,89.42,757.44,59.11,27.09,43.37,72.69,157.15,988.68,907.66,1271.79,1271.77,1652.38,535.68,1066.08,707.04,868.80,1112.98
3,NON-CONVENTIONAL ENERGY,0.00,0.00,1.70,4.14,1.27,1.35,2.44,58.82,125.88,622.52,214.40,452.17,1106.52,414.25,615.95,776.51,783.57
4,COAL PRODUCTION,0.00,0.00,0.00,0.04,0.00,9.14,1.30,14.08,0.22,0.00,0.00,0.00,0.00,2.96,0.00,0.00,0.00

In [ ]:
data.shape

(63, 18)

In [ ]:
data.tail()

,Sector,2000-01,2001-02,2002-03,2003-04,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17
58,PRINTING OF BOOKS (INCLUDING LITHO PRINTING IN...,0.00,0.00,6.30,0.00,0.06,9.90,20.04,35.54,31.61,70.51,36.63,47.39,14.34,113.78,72.58,122.81,53.17
59,COIR,0.00,0.00,0.00,0.00,0.47,0.59,0.04,0.01,0.00,0.25,0.10,0.55,0.15,0.54,1.36,0.00,0.00
60,CONSTRUCTION (INFRASTRUCTURE) ACTIVITIES,0.00,0.00,0.00,0.00,0.00,0.93,64.06,182.92,172.70,324.56,675.07,386.28,283.89,485.37,870.25,4510.71,1860.73
61,"CONSTRUCTION DEVELOPMENT: Townships, housing, ...",24.33,51.75,36.10,47.04,152.06,228.71,1392.95,3887.33,4657.51,5466.13,1663.03,3140.78,1332.49,1226.05,769.14,112.55,105.14
62,MISCELLANEOUS INDUSTRIES,832.07,221.37,218.76,235.48,121.83,164.76,304.87,528.42,1549.70,1147.56,1475.97,813.38,229.49,468.74,765.88,668.77,296.40

In [ ]:
data.columns

Index(['Sector', '2000-01', '2001-02', '2002-03', '2003-04', '2004-05',
       '2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11',
       '2011-12', '2012-13', '2013-14', '2014-15', '2015-16', '2016-17'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Sector   63 non-null     object
 1   2000-01  63 non-null     float64
 2   2001-02  63 non-null     float64
 3   2002-03  63 non-null     float64
 4   2003-04  63 non-null     float64
 5   2004-05  63 non-null     float64
 6   2005-06  63 non-null     float64
 7   2006-07  63 non-null     float64
 8   2007-08  63 non-null     float64
 9   2008-09  63 non-null     float64
 10  2009-10  63 non-null     float64
 11  2010-11  63 non-null     float64
 12  2011-12  63 non-null     float64
 13  2012-13  63 non-null     float64
 14  2013-14  63 non-null     float64
 15  2014-15  63 non-null     float64
 16  2015-16  63 non-null     float64
 17  2016-17  63 non-null     float64
dtypes: float64(17), object(1)
memory usage: 9.0+ KB

In [ ]:
data.describe()

,2000-01,2001-02,2002-03,2003-04,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17
count,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000
mean,37.757302,63.931587,42.925714,34.727778,51.090317,87.932540,198.281905,390.085714,498.348571,410.069524,339.413810,557.472698,355.930000,385.703492,490.959841,634.936349,690.131111
std,112.227860,157.878737,86.606439,67.653735,101.934873,206.436967,686.783115,1026.249935,1134.649040,926.814626,627.141139,1031.474056,778.091368,658.429944,837.787060,1335.307706,1411.965354
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.200000,0.215000,0.715000,1.230000,4.160000,9.950000,11.950000,7.880000,8.430000,22.720000,15.115000,16.610000,33.800000,30.000000,19.905000
50%,4.030000,5.070000,11.010000,6.370000,9.090000,22.620000,25.820000,58.820000,84.880000,69.740000,58.070000,129.360000,95.410000,113.780000,177.220000,159.130000,110.860000
75%,23.510000,44.830000,36.555000,38.660000,43.205000,63.855000,108.325000,279.270000,383.320000,341.595000,304.280000,593.525000,288.025000,473.060000,595.390000,519.070000,741.220000
max,832.070000,873.230000,419.960000,368.320000,527.900000,1359.970000,4713.780000,6986.170000,6183.490000,5466.130000,3296.090000,5215.980000,4832.980000,3982.890000,4443.260000,6889.460000,8684.070000

In [ ]:
data.style.set_caption("Amounts in US $ Millions").format(precision=2)

In [ ]:
data.isnull().sum()

Sector     0
2000-01    0
2001-02    0
2002-03    0
2003-04    0
2004-05    0
2005-06    0
2006-07    0
2007-08    0
2008-09    0
2009-10    0
2010-11    0
2011-12    0
2012-13    0
2013-14    0
2014-15    0
2015-16    0
2016-17    0
dtype: int64

In [ ]:
data.duplicated().sum()

0

Creating a function to convert Dollars to Rupees

In [ ]:
rates = [45.68,47.69,48.39,45.95,44.93,44.27,45.24,40.26,45.99,47.44,45.56,47.92,54.40,60.50,61.14,65.46,67.07]
year = ['2000-01', '2001-02', '2002-03', '2003-04', '2004-05', '2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11',
       '2011-12', '2012-13', '2013-14', '2014-15', '2015-16', '2016-17']
sector = ['Sector']
def conv (df, year, rates):
  for i in year:
    df[i] = df[i] * rates[year.index(i)]/10
  return df

In [ ]:
data_dollar = data.copy()
datars= conv(data, year, rates)
datars.style.set_caption("Amount in Indian Crore Rupees").format(precision =2)

In [ ]:
pivot = pd.melt(data_dollar, id_vars = sector, value_vars= year, var_name = "Year", value_name = "Investment ($ million)", ignore_index = True)
pivot = round(pivot, 2)
pivot

,Sector,Year,Investment ($ million)
0,METALLURGICAL INDUSTRIES,2000-01,22.69
1,MINING,2000-01,1.32
2,POWER,2000-01,89.42
3,NON-CONVENTIONAL ENERGY,2000-01,0.00
4,COAL PRODUCTION,2000-01,0.00
...,...,...,...
1066,PRINTING OF BOOKS (INCLUDING LITHO PRINTING IN...,2016-17,53.17
1067,COIR,2016-17,0.00
1068,CONSTRUCTION (INFRASTRUCTURE) ACTIVITIES,2016-17,1860.73
1069,"CONSTRUCTION DEVELOPMENT: Townships, housing, ...",2016-17,105.14
1070,MISCELLANEOUS INDUSTRIES,2016-17,296.40

In [ ]:
pivotrs= pd.melt(datars, id_vars = sector, value_vars= year, var_name = "Year", value_name= "Investment (Rs Crore)", ignore_index = True)
pivotrs = round(pivotrs, 2)
pivotrs

,Sector,Year,Investment (Rs Crore)
0,METALLURGICAL INDUSTRIES,2000-01,103.65
1,MINING,2000-01,6.03
2,POWER,2000-01,408.47
3,NON-CONVENTIONAL ENERGY,2000-01,0.00
4,COAL PRODUCTION,2000-01,0.00
...,...,...,...
1066,PRINTING OF BOOKS (INCLUDING LITHO PRINTING IN...,2016-17,356.61
1067,COIR,2016-17,0.00
1068,CONSTRUCTION (INFRASTRUCTURE) ACTIVITIES,2016-17,12479.92
1069,"CONSTRUCTION DEVELOPMENT: Townships, housing, ...",2016-17,705.17
1070,MISCELLANEOUS INDUSTRIES,2016-17,1987.95

In [ ]:
merg = pivotrs.merge(pivot, how = "left")
merg

,Sector,Year,Investment (Rs Crore),Investment ($ million)
0,METALLURGICAL INDUSTRIES,2000-01,103.65,22.69
1,MINING,2000-01,6.03,1.32
2,POWER,2000-01,408.47,89.42
3,NON-CONVENTIONAL ENERGY,2000-01,0.00,0.00
4,COAL PRODUCTION,2000-01,0.00,0.00
...,...,...,...,...
1066,PRINTING OF BOOKS (INCLUDING LITHO PRINTING IN...,2016-17,356.61,53.17
1067,COIR,2016-17,0.00,0.00
1068,CONSTRUCTION (INFRASTRUCTURE) ACTIVITIES,2016-17,12479.92,1860.73
1069,"CONSTRUCTION DEVELOPMENT: Townships, housing, ...",2016-17,705.17,105.14
1070,MISCELLANEOUS INDUSTRIES,2016-17,1987.95,296.40

In [ ]:
sort = merg.sort_values(['Sector', 'Year'], ignore_index = True)
sort

,Sector,Year,Investment (Rs Crore),Investment ($ million)
0,AGRICULTURAL MACHINERY,2000-01,16.63,3.64
1,AGRICULTURAL MACHINERY,2001-02,4.96,1.04
2,AGRICULTURAL MACHINERY,2002-03,65.23,13.48
3,AGRICULTURAL MACHINERY,2003-04,218.45,47.54
4,AGRICULTURAL MACHINERY,2004-05,0.00,0.00
...,...,...,...,...
1066,VEGETABLE OILS AND VANASPATI,2012-13,589.64,108.39
1067,VEGETABLE OILS AND VANASPATI,2013-14,130.38,21.55
1068,VEGETABLE OILS AND VANASPATI,2014-15,906.95,148.34
1069,VEGETABLE OILS AND VANASPATI,2015-16,224.00,34.22
1070,VEGETABLE OILS AND VANASPATI,2016-17,727.37,108.45

In [ ]:
sort = sort[['Sector', 'Investment ($ million)', 'Investment (Rs Crore)']].replace(["CONSTRUCTION DEVELOPMENT: Townships, housing, built-up infrastructure and construction-development projects"
                              ,"SERVICES SECTOR (Fin.,Banking,Insurance,Non Fin/Business,Outsourcing,R&D,Courier,Tech. Testing and Analysis, Other)",
                              "TEA AND COFFEE (PROCESSING & WAREHOUSING COFFEE & RUBBER)"],
                               ["CONSTRUCTION DEVELOPMENT","SERVICES SECTOR",'TEA AND COFFEE']                                     )

In [ ]:
sectorwise = sort.groupby("Sector").sum()
sectorwise.sort_values(by ="Investment ($ million)", ascending = False)

,Investment ($ million),Investment (Rs Crore)
Sector,,
SERVICES SECTOR,59476.49,316347.59
COMPUTER SOFTWARE & HARDWARE,24669.49,137276.82
CONSTRUCTION DEVELOPMENT,24293.09,115185.97
TELECOMMUNICATIONS,23946.01,130966.04
AUTOMOBILE INDUSTRY,16673.92,92622.66
...,...,...
PHOTOGRAPHIC RAW FILM AND PAPER,67.28,278.37
COAL PRODUCTION,27.74,122.13
"MATHEMATICAL,SURVEYING AND DRAWING INSTRUMENTS",7.98,41.61
DEFENCE INDUSTRIES,5.12,26.09
COIR,4.06,21.64

In [ ]:
merg.to_csv("FDI clean.csv", index = False)

In [ ]:
d = pd.read_csv("/content/FDI clean.csv")
d.tail()

,Sector,Year,Investment (Rs Crore),Investment ($ million)
1066,PRINTING OF BOOKS (INCLUDING LITHO PRINTING IN...,2016-17,356.61,53.17
1067,COIR,2016-17,0.00,0.00
1068,CONSTRUCTION (INFRASTRUCTURE) ACTIVITIES,2016-17,12479.92,1860.73
1069,"CONSTRUCTION DEVELOPMENT: Townships, housing, ...",2016-17,705.17,105.14
1070,MISCELLANEOUS INDUSTRIES,2016-17,1987.95,296.40

In [ ]:
sectorwise['year'] = '2000-2017'
sectorwise = sectorwise[['year', 'Investment ($ million)', 'Investment (Rs Crore)']]

sectorwise['Total Inflow %'] = (sectorwise['Investment (Rs Crore)']/sectorwise['Investment (Rs Crore)'].sum())* 100

<ipython-input-64-28208442a69d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sectorwise['Total Inflow %'] = (sectorwise['Investment (Rs Crore)']/sectorwise['Investment (Rs Crore)'].sum())* 100

In [ ]:
sortval= sectorwise.sort_values('Investment (Rs Crore)', ascending = False)
sortval.style.set_caption("Sector - Wise Investment Inflows").format(precision = 2)
sortval

,year,Investment ($ million),Investment (Rs Crore),Total Inflow %
Sector,,,,
SERVICES SECTOR,2000-2017,59476.49,316347.59,17.654504
COMPUTER SOFTWARE & HARDWARE,2000-2017,24669.49,137276.82,7.661048
TELECOMMUNICATIONS,2000-2017,23946.01,130966.04,7.308861
CONSTRUCTION DEVELOPMENT,2000-2017,24293.09,115185.97,6.428218
AUTOMOBILE INDUSTRY,2000-2017,16673.92,92622.66,5.169020
...,...,...,...,...
PHOTOGRAPHIC RAW FILM AND PAPER,2000-2017,67.28,278.37,0.015535
COAL PRODUCTION,2000-2017,27.74,122.13,0.006816
"MATHEMATICAL,SURVEYING AND DRAWING INSTRUMENTS",2000-2017,7.98,41.61,0.002322
DEFENCE INDUSTRIES,2000-2017,5.12,26.09,0.001456
COIR,2000-2017,4.06,21.64,0.001208